name = "dcdc"
product-name = "DCDC"

before-packaging-command = "cargo build --release"
out-dir = "./dist"
icons = ["icons/icon.png"]
identifier = "com.derekreese.dcdc"
version = "0.1.0"

[[binaries]]
path = "../target/release/dcdc"
main = true
